### ISSUE TITLE
SystemError: NULL result without error in PyObject_Call

### ISSUE THREAD

**Issue by leenaraz** [VisionLearningGroup/JEDDi-Net#1]
This is the error i get when i run
    bash ./experiments/denseCap_jeddiNet_end2end/script_train.sh
Here is the error

Traceback (most recent call last):
  File "./experiments/denseCap_jeddiNet_end2end/train_net.py", line 99, in <module>
    max_iters=args.max_iters)
  File "/home/user4/mainpro/JEDDi-Net/experiments/denseCap_jeddiNet_end2end/../../lib/tdcnn/train_end2end.py", line 163, in train_net
    sw = SolverWrapper(solver_prototxt, roidb, output_dir, pretrained_model=pretrained_model, detection_pretrained_model=detection_pretrained_model)
  File "/home/user4/mainpro/JEDDi-Net/experiments/denseCap_jeddiNet_end2end/../../lib/tdcnn/train_end2end.py", line 45, in __init__
    self.solver = caffe.SGDSolver(solver_prototxt)
SystemError: NULL result without error in PyObject_Call

Please help me solve this

**Comment by huijuan88** [comment]
It is probably because of path.

On Apr 17, 2019, at 09:15, leenaraz <notifications@github.com<mailto:notifications@github.com>> wrote:


This is the error i get when i run
bash ./experiments/denseCap_jeddiNet_end2end/script_train.sh
Here is the error

Traceback (most recent call last):
File "./experiments/denseCap_jeddiNet_end2end/train_net.py", line 99, in
max_iters=args.max_iters)
File "/home/user4/mainpro/JEDDi-Net/experiments/denseCap_jeddiNet_end2end/../../lib/tdcnn/train_end2end.py", line 163, in train_net
sw = SolverWrapper(solver_prototxt, roidb, output_dir, pretrained_model=pretrained_model, detection_pretrained_model=detection_pretrained_model)
File "/home/user4/mainpro/JEDDi-Net/experiments/denseCap_jeddiNet_end2end/../../lib/tdcnn/train_end2end.py", line 45, in init
self.solver = caffe.SGDSolver(solver_prototxt)
SystemError: NULL result without error in PyObject_Call

Please help me solve this

**Comment by leenaraz** [comment]
Thankyou Sir,
I have some doubts and i hope you will please help me with it.

1.Where am i supposed to placd the activitynet videos and fps files fof the
training?

2. Have you implemented a demo to pass this model to a video and get the
output? If yes, can you please share the code with me.

Thankyou
